version: 2

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: css-trimmer
    main: ./cmd/css-trimmer/main.go
    binary: css-trimmer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
   - format: tar.gz
     name_template: '{{ .ProjectName }}_{{ .Version }}_{{ replace .Os "darwin" "macOS" | replace .Os "linux" "Linux" | replace .Os "windows" "Windows" }}_{{ replace .Arch "amd64" "x86_64" }}'
     format_overrides:
       - goos: windows
         format: zip

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: auto
